name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v5

    - name: Create conda environment
      uses: mamba-org/setup-micromamba@v2
      with:
        cache-downloads: true
        micromamba-version: "latest"
        environment-file: ci/environment.yml

    - name: Install slv (editable)
      run: pip install --no-deps -e .

    - name: Lint with ruff
      run: ruff check --output-format=github src/slv

    - name: Type checking with pyright
      if: ${{ !cancelled() }}
      run: pyright src/slv

    - name: Check docstring coverage
      if: ${{ !cancelled() }}
      run: docstr-coverage src/slv --skip-magic --skip-init
