name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v5

    - name: Create conda environment
      uses: mamba-org/setup-micromamba@v2
      with:
        cache-downloads: true
        micromamba-version: "latest"
        environment-file: ci/environment.yml
        create-args: >-
          python=${{ matrix.python-version }}

    - name: Install slv (editable)
      run: pip install --no-deps -e .

    - name: Run tests with pytest
      run: pytest -v --cov=slv --junitxml=junit.xml -o junit_family=legacy

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      if: ${{ matrix.python-version == '3.12' && !cancelled() }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload test results to Codecov
      if: ${{ matrix.python-version == '3.12' && !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
